import { Collection, Space, Submission, TeamResource } from './types'

export const TEAM_SPACES: Space[] = [
  {
    id: 'ai-studio',
    name: 'AI Studio',
    description: '沉淀团队常用 skills、agents 与 AI workflow。',
    lead: '张工',
    memberCount: 12,
    resourceCount: 8,
    theme: 'from-fuchsia-500/20 to-cyan-500/20',
  },
  {
    id: 'engineering-core',
    name: 'Engineering Core',
    description: '研发日常高频工具与交付基础设施入口。',
    lead: '王工',
    memberCount: 18,
    resourceCount: 11,
    theme: 'from-blue-500/20 to-emerald-500/20',
  },
  {
    id: 'knowledge-hub',
    name: 'Knowledge Hub',
    description: '模板、规范、知识文档与团队 Playbook 集合。',
    lead: '李工',
    memberCount: 9,
    resourceCount: 6,
    theme: 'from-amber-500/20 to-pink-500/20',
  },
]

export const TEAM_COLLECTIONS: Collection[] = [
  {
    id: 'ai-writing',
    spaceId: 'ai-studio',
    name: 'AI Writing Stack',
    description: '面向内容创作和文档整理的 AI 能力组合。',
    owner: 'AI 平台组',
    resourceIds: ['feishu-doc-skill', 'release-agent'],
  },
  {
    id: 'release-kit',
    spaceId: 'engineering-core',
    name: '发布工具包',
    description: '覆盖修改整理、发布说明与协作通知的工具集合。',
    owner: '开发效能组',
    resourceIds: ['release-agent', 'github'],
  },
  {
    id: 'knowledge-starter',
    spaceId: 'knowledge-hub',
    name: '知识入门包',
    description: '产品文档模板与 incident playbook 基础集合。',
    owner: '产品平台组',
    resourceIds: ['prd-template', 'incident-playbook'],
  },
]

export const SEED_RESOURCES: TeamResource[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    tagline: '终端中的 AI 编程协作入口',
    description: '团队默认的 AI 编程助手，可直接搜索代码、编辑文件、运行命令与管理开发任务。',
    resourceType: 'desktop',
    domain: 'ai-workspace',
    capabilityLayer: 'assistant',
    url: 'https://docs.anthropic.com/claude-code',
    tags: ['AI', '编程', '终端'],
    owner: '开发效能组',
    team: 'Platform',
    visibility: 'team',
    status: 'recommended',
    spaces: ['ai-studio', 'engineering-core'],
    tasks: ['代码生成', '仓库重构', '问题排查'],
    integrations: ['GitHub', 'Terminal'],
    surfaces: ['macOS', 'CLI'],
    submittedBy: '张工',
    updatedAt: '2026-03-20',
    featured: true,
    favorited: false,
    actionLabel: '打开文档',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'AI 原生编辑器工作台',
    description: '适合多文件编辑、代码解释和快速原型开发的 AI 编辑器。',
    resourceType: 'desktop',
    domain: 'engineering',
    capabilityLayer: 'assistant',
    url: 'https://cursor.sh',
    tags: ['AI', '编辑器', '代码'],
    owner: '开发效能组',
    team: 'Platform',
    visibility: 'team',
    status: 'active',
    spaces: ['engineering-core'],
    tasks: ['原型开发', '多文件编辑'],
    integrations: ['GitHub'],
    surfaces: ['macOS', 'Windows'],
    submittedBy: '李工',
    updatedAt: '2026-03-18',
    actionLabel: '前往官网',
  },
  {
    id: 'team-toolbox-web',
    name: 'Team Toolbox Web',
    tagline: '团队能力平台的 Web 门户入口',
    description: '统一承载工具、文档、AI 能力和协作资源的共享门户。',
    resourceType: 'webapp',
    domain: 'collaboration',
    capabilityLayer: 'resource',
    url: 'https://toolbox.internal',
    tags: ['门户', '共享', '导航'],
    owner: '产品平台组',
    team: 'Platform',
    visibility: 'team',
    status: 'beta',
    spaces: ['engineering-core', 'knowledge-hub'],
    tasks: ['资源导航', '团队分享'],
    integrations: ['SSO', '知识库'],
    surfaces: ['Web'],
    submittedBy: '赵工',
    updatedAt: '2026-03-25',
    featured: true,
    actionLabel: '进入平台',
  },
  {
    id: 'feishu-doc-skill',
    name: 'Feishu Doc Skill',
    tagline: '飞书文档读写能力',
    description: '为大模型工作流提供飞书文档创建、编辑、读取与权限管理能力。',
    resourceType: 'skill',
    domain: 'ai-workspace',
    capabilityLayer: 'assistant',
    url: 'https://clawhub.com',
    tags: ['飞书', '文档', 'Skill'],
    owner: 'AI 平台组',
    team: 'AI Platform',
    visibility: 'restricted',
    status: 'recommended',
    spaces: ['ai-studio', 'knowledge-hub'],
    tasks: ['文档生成', '知识同步'],
    integrations: ['Feishu'],
    surfaces: ['Model Context Protocol'],
    submittedBy: '张工',
    updatedAt: '2026-03-12',
    aiType: 'skill',
    aiInputs: ['文档标题', '操作指令', '上下文内容'],
    aiOutputs: ['文档正文', '编辑结果', '权限配置'],
    modelOrRuntime: 'Claude 3.5 Sonnet + Feishu Graph',
    invocationMethod: 'Skill 调用（MCP 通道）',
    permissions: ['飞书企业管理员授权', '文档读写权限'],
    relatedResources: ['team-toolbox-web'],
    examples: ['“创建周会纪要草稿”', '“把 PRD 模板同步到飞书文档”'],
    featured: true,
    actionLabel: '查看 Skill',
  },
  {
    id: 'release-agent',
    name: 'Release Agent',
    tagline: '自动整理发布说明与变更摘要',
    description: '连接 GitHub、文档与消息系统，自动生成发布说明并同步到团队频道。',
    resourceType: 'agent',
    domain: 'operations',
    capabilityLayer: 'workflow',
    url: 'https://agents.internal/release',
    tags: ['Agent', '发布', '自动化'],
    owner: '研发效能组',
    team: 'Platform',
    visibility: 'restricted',
    status: 'beta',
    spaces: ['ai-studio', 'engineering-core'],
    tasks: ['发布说明', '变更同步'],
    integrations: ['GitHub', 'Feishu'],
    surfaces: ['Web', 'Webhook'],
    submittedBy: '王工',
    updatedAt: '2026-03-22',
    aiType: 'agent',
    aiInputs: ['Pull Request 列表', '变更日志', '发布计划'],
    aiOutputs: ['发布说明初稿', '公告摘要'],
    modelOrRuntime: 'Claude 3 Opus + Workflow Orchestrator',
    invocationMethod: 'Agent 平台工作流',
    permissions: ['GitHub 读权限', '飞书群推送'],
    relatedResources: ['github'],
    examples: ['“生成 3 月版本发布说明并通知研发群”'],
    actionLabel: '打开 Agent',
  },
  {
    id: 'github',
    name: 'GitHub',
    tagline: '代码协作与发布入口',
    description: '代码托管、PR 协作、Actions CI/CD 与 Issue 跟踪的核心平台。',
    resourceType: 'link',
    domain: 'engineering',
    capabilityLayer: 'resource',
    url: 'https://github.com',
    tags: ['代码', '协作', '开源'],
    owner: '研发效能组',
    team: 'Platform',
    visibility: 'public',
    status: 'active',
    spaces: ['engineering-core'],
    tasks: ['代码协作', 'CI/CD'],
    integrations: ['Actions'],
    surfaces: ['Web'],
    submittedBy: '张工',
    updatedAt: '2026-03-10',
    actionLabel: '打开 GitHub',
  },
  {
    id: 'openclaw-feishu-plugin',
    name: 'OpenClaw Feishu Plugin',
    tagline: '连接飞书频道的 AI 插件',
    description: '支持在飞书群聊中调用 AI 助手、接收通知和执行团队工作流。',
    resourceType: 'plugin',
    domain: 'collaboration',
    capabilityLayer: 'assistant',
    url: 'https://docs.openclaw.ai/channels/feishu',
    tags: ['飞书', '插件', 'AI'],
    owner: 'AI 平台组',
    team: 'AI Platform',
    visibility: 'team',
    status: 'active',
    spaces: ['ai-studio'],
    tasks: ['IM 协作', '消息触达'],
    integrations: ['Feishu'],
    surfaces: ['Web'],
    submittedBy: '张工',
    updatedAt: '2026-03-19',
    aiType: 'plugin',
    aiInputs: ['频道消息', '用户指令'],
    aiOutputs: ['助手回复', '自动通知'],
    modelOrRuntime: 'OpenClaw Runtime',
    invocationMethod: '插件安装后 Slash 命令',
    permissions: ['飞书 Bot 管理权限'],
    relatedResources: ['feishu-doc-skill'],
    examples: ['“在研发群中调用 AI 总结讨论”'],
    actionLabel: '查看插件',
  },
  {
    id: 'batch-rename-script',
    name: '批量重命名脚本',
    tagline: '文件处理自动化脚本',
    description: '支持批量重命名、预览和回滚，适合处理规范化文件命名。',
    resourceType: 'script',
    domain: 'operations',
    capabilityLayer: 'workflow',
    url: 'https://github.com/example/batch-rename',
    tags: ['Python', '文件处理'],
    owner: '效率工具组',
    team: 'Ops',
    visibility: 'team',
    status: 'active',
    spaces: ['engineering-core'],
    tasks: ['批量处理', '命名规范'],
    surfaces: ['CLI'],
    submittedBy: '王工',
    updatedAt: '2026-03-14',
    actionLabel: '查看脚本',
  },
  {
    id: 'prd-template',
    name: 'PRD 文档模板',
    tagline: '标准化需求文档模板',
    description: '沉淀需求背景、用户故事、验收标准等结构的产品文档模板。',
    resourceType: 'file',
    domain: 'knowledge',
    capabilityLayer: 'knowledge',
    url: 'https://example.com/prd-template',
    tags: ['模板', '产品', '文档'],
    owner: '产品运营组',
    team: 'Product',
    visibility: 'team',
    status: 'recommended',
    spaces: ['knowledge-hub'],
    tasks: ['文档规范', 'PRD'],
    surfaces: ['Web'],
    submittedBy: '张工',
    updatedAt: '2026-03-08',
    actionLabel: '打开模板',
  },
  {
    id: 'incident-playbook',
    name: 'Incident Playbook',
    tagline: '线上故障协同处置手册',
    description: '包含值班响应、升级路径、公告模板与复盘清单的标准化处置手册。',
    resourceType: 'playbook',
    domain: 'operations',
    capabilityLayer: 'knowledge',
    url: 'https://example.com/incident-playbook',
    tags: ['手册', '故障', 'SOP'],
    owner: 'SRE 团队',
    team: 'Ops',
    visibility: 'team',
    status: 'recommended',
    spaces: ['knowledge-hub', 'engineering-core'],
    tasks: ['故障响应', '复盘'],
    surfaces: ['Web'],
    submittedBy: '李工',
    updatedAt: '2026-03-24',
    featured: true,
    actionLabel: '查看手册',
  },
]

export const SEED_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-1',
    resource: {
      name: 'Prompt Gallery',
      tagline: '团队通用 Prompt 模板集合',
      description: '沉淀评审过的 Prompt 模板，支持按场景快速检索并复制使用。',
      resourceType: 'file',
      domain: 'ai-workspace',
      capabilityLayer: 'knowledge',
      url: 'https://example.com/prompt-gallery',
      tags: ['Prompt', 'AI'],
      owner: 'AI 平台组',
      team: 'AI Platform',
      visibility: 'team',
      status: 'active',
      spaces: ['ai-studio'],
      tasks: ['Prompt 复用'],
      integrations: ['Notion'],
      surfaces: ['Web'],
      submittedBy: '赵工',
      featured: false,
      favorited: false,
      actionLabel: '查看模板',
    },
    submittedAt: '2026-03-28T09:30:00Z',
    submittedBy: '赵工',
    status: 'pending',
  },
]
